//@version=3
// Copyright (c) 2019-present, Alex Orekhov (everget)
// BitMEX Withdrawals Cutoff Time script may be freely distributed under the terms of GPL-3.0 license.
study("BitMEX Withdrawals Cutoff Time", overlay=true)

transparency = input(title="Transparency", minval=0, defval=70)

cutoff = hour(time) == 13
transparent = color(white, 100)

bgcolor(cutoff ? #f57f17 : transparent, title="Cutoff Time", transp=transparency)