//@version=4
// Copyright (c) 2019-present, Alex Orekhov (everget)
// Kagi Chart Identifier script may be freely distributed under the terms of the GPL-3.0 license.
study("Kagi Chart Identifier", overlay=true)

var ocCount = -1
if open[1] == close or close[1] == open
    ocCount := ocCount + 1

var hCount = -1
if open == high or close == high
    hCount := hCount + 1

var lCount = -1
if open == low or close == low
    lCount := lCount + 1

isKagi = hCount == bar_index and lCount == bar_index and ocCount == bar_index - 1

labelText = isKagi ? "This is Kagi Chart" : "This is not Kagi Chart"
stats = "\n------------------------------" +
         "\nBar Index: " + tostring(int(bar_index)) +
         "\nO==C Candles: " + tostring(ocCount) +
         "\nOC==H Candles: " + tostring(hCount) +
         "\nOC==L Candles: " + tostring(lCount)
labelColor = #1e90ff
whiteColor = color.white

var label kagiLabel = label.new(
     x=bar_index,
     y=na,
     text="",
     color=labelColor,
     textcolor=whiteColor,
     style=label.style_labeldown,
     size=size.normal
     )

label.set_text(kagiLabel, labelText + stats)
label.set_xy(kagiLabel, bar_index, highest(close, 10))
