//@version=3
// Copyright (c) 2019-present, Alex Orekhov (everget)
// Percentrank Bug script may be freely distributed under the terms of the GPL-3.0 license.
study("Percentrank Bug")

src = volume
length = input(14)

pr = percentrank(src, length)
plot(pr, title="Built-in", color=red)

_percentrank(src, length) =>
    count = 0
    for i = 1 to length
        count := count + (src >= nz(src[i]) ? 1 : 0)
    pr = 100 * count / length

pr2 = _percentrank(src, length)

plot(pr2, title="Shim", color=green)
