//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Chande Momentum Oscillator script may be freely distributed under the MIT license.
study("Chande Momentum Oscillator", shorttitle="ChandeMO")

length = input(title="CMO Length", type=integer, defval=9, minval=1)
overBoughtLevel = input(title="CMO Overbought", type=integer, defval=50)
overSoldLevel = input(title="CMO Oversold", type=integer, defval=-50)
src = input(title="CMO Source", type=source, defval=close)

smoothedMomentum = sma(abs(close - close[1]), length)

cmo = 100 * ((close - nz(close[length])) / (smoothedMomentum * length))
pos = 0.0
pos := iff(cmo > overBoughtLevel, 1,
	   iff(cmo <= overSoldLevel, -1, nz(pos[1], 0)))

hline(0, color=gray, linestyle=line)

overBoughtBand = hline(overBoughtLevel, linestyle=dashed, color=gray)
overSoldBand = hline(overSoldLevel, linestyle=dashed, color=gray)
fill(overBoughtBand, overSoldBand, color=#f9cb9c0f)

# // Chande Momentum Oscillator
# f1(m) => m >= 0.0 ? m : 0.0
# f2(m) => m >= 0.0 ? 0.0 : -m

# diff = change(src)
# upSum = sum(f1(diff), length)
# downSum = sum(f2(diff), length)

# cmo = (upSum - downSum) / (upSum + downSum)

plot(cmo, title="CMO", color=#0094ff, transp=0)
