//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Ergodic Oscillator script may be freely distributed under the MIT license.
study("Ergodic Oscillator", shorttitle="EOSC")

firstSmoothingLength = input(title="1st Smoothing Length", type=integer, minval=1, defval=8)
secondSmoothingLength = input(title="2nd Smoothing Length", type=integer, minval=1, defval=5)
signalLength = input(title="Signal Length", type=integer, minval=1, defval=5)
ergodicLength = input(title="Ergodic Length", type=integer, minval=1, defval=5)
ergodicSignalLength = input(title="Ergodic Signal Length", type=integer, minval=1, defval=14)
overboughtLevel = input(title="Overbought Level", type=integer, defval=20)
oversoldLevel = input(title="Oversold Level", type=integer, defval=-20)
src = input(title="Source", type=source, defval=close)

momentum = change(src)

ema1 = ema(momentum, firstSmoothingLength)
ema1Abs = ema(abs(momentum), firstSmoothingLength)

ema2 = ema(ema1, secondSmoothingLength)
ema2Abs = ema(abs(ema1Abs), secondSmoothingLength)

tsi = 100 * ema2 / ema2Abs

signal = ema(tsi, signalLength)

ergodic = ema(signal, ergodicLength)

ergodicSignal = ema(ergodic, ergodicSignalLength)

plot(ergodic, title="Ergodic", linewidth=2, color=#3c78d8, transp=0)
plot(ergodicSignal, title="Signal", linewidth=2, color=#cc0000, transp=0)

hline(overboughtLevel, title="Overbought Level", linestyle=dotted, linewidth=2, color=#0ebb23)
hline(oversoldLevel, title="Oversold Level", linestyle=dotted, linewidth=2, color=#ff9370)
