//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Kairi Relative Index script may be freely distributed under the MIT license.
study("Kairi Relative Index", shorttitle="KRI")

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

kri = 100 * (src - sma(src, length)) / sma(src, length)

plot(kri, title="KRI", linewidth=1, color=#134f5c, transp=0)

hline(0, title="Zero Level", linestyle=dotted, color=#989898)
