//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Normalized Relative Vigor Index script may be freely distributed under the MIT license.
study("Normalized Relative Vigor Index", shorttitle="NRVGI")

length = input(title="Length", type=integer, defval=10, minval=1)
applyFilling = input(title="Apply Filling ?", type=bool, defval=false)

rvgi = sum(swma(close - open), length) / sum(swma(high - low), length)
signal = swma(rvgi)

rvgiPlot = plot(100 * rvgi, title="NRVGI", color=green, transp=0)
signalPlot = plot(100 * signal, title="Signal", color=red, transp=0)

fillColor = applyFilling ? (rvgi > signal ? #0ebb23 : #cc0000) : color(white, 100)
fill(rvgiPlot, signalPlot, color=fillColor, transp=0)
