//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// OSC Oscillator script may be freely distributed under the MIT license.
study("OSC Oscillator", shorttitle="OSC")

slowLength = input(title="Slow Length", type=integer, minval=1, defval=14)
fastLength = input(title="Fast Length", type=integer, minval=1, defval=7)
src = input(title="Source", type=source, defval=close)

osc = sma(src, slowLength) - sma(src, fastLength)

oscColor = osc >= 0.0 ? #0ebb23 : #ff0000
plot(osc, title="OSC", linewidth=2, color=oscColor, transp=0)

hline(0, title="Zero Level", linestyle=dotted, color=#989898)
