//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Percentage Price Oscillator indicator script may be freely distributed under the MIT license.
study("Percentage Price Oscillator", shorttitle="PPO")

fastLength = input(title="Fast Length", type=integer, defval=12, minval=1)
slowLength = input(title="Slow Length", type=integer, defval=26, minval=1)
signalLength = input(title="Signal Length", type=integer, defval=9, minval=1)
applyFilling = input(title="Apply Filling ?", type=bool, defval=false)
src = input(title="Source", type=source, defval=close)

ppo = 100 * (ema(src, fastLength) - ema(src, slowLength)) / ema(src, slowLength)

signal = ema(ppo, signalLength)

hist = ppo - signal

plot(hist, title="Histogram", style=histogram, transp=0, color=#ff006e)
ppoPlot = plot(ppo, title="PPO", transp=0, color=#0094ff)
signalPlot = plot(signal, title="Signal", transp=0, color=#ff6a00)

fillColor = applyFilling ? (ppo > signal ? #0ebb23 : #cc0000) : color(white, 100)
fill(ppoPlot, signalPlot, color=fillColor, transp=0)
