//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Pretty Good Oscillator script may be freely distributed under the MIT license.
study("Pretty Good Oscillator", shorttitle="PGO")

length = input(title="Length", type=integer, defval=14, minval=1)
upperLevel = input(title="Upper Band", type=float, defval=2.0)
lowerLevel = input(title="Lower Band", type=float, defval=-2.0)
src = input(title="Source", type=source, defval=close)

pgo = (src - sma(src, length)) / atr(length)

upperBand = hline(title="Upper Band", price=upperLevel, linestyle=dashed, color=gray)
lowerBand = hline(title="Lower Band", price=lowerLevel, linestyle=dashed, color=gray)

fill(title="Background", hline1=upperBand, hline2=lowerBand, color=color(#a61c00, 95))

pgoColor = pgo > upperLevel ? #0ebb23 : pgo < lowerLevel ? #cc0000 : #1155cc

plot(pgo, title="PGO", linewidth=1, color=pgoColor, transp=0)

hline(0, title="Zero Level", linestyle=dotted)
