//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Pring Special K script may be freely distributed under the MIT license.
study("Pring Special K", shorttitle="PSK")

src = input(title="Source", type=source, defval=close)

psk = sma(roc(src, 10), 10) +
	sma(roc(src, 10), 15) * 2 +
	sma(roc(src, 10), 20) * 3 +
	sma(roc(src, 15), 30) * 4 +
	sma(roc(src, 50), 40) +
	sma(roc(src, 65), 65) * 2 +
	sma(roc(src, 75), 75) * 3 +
	sma(roc(src, 100), 100) * 4 +
	sma(roc(src, 130), 195) +
	sma(roc(src, 130), 265) * 2 +
	sma(roc(src, 130), 390) * 3 +
	sma(roc(src, 195), 530) * 4

pskColor = psk >= 0.0 ? #0ebb23 : #ff0000

plot(psk, title="PSK", linewidth=2, color=pskColor, transp=0)

hline(0, title="Zero Level", linestyle=dotted)
