//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Random Walk Index script may be freely distributed under the MIT license.
study("Random Walk Index", shorttitle="RWI")

length = input(title="Length", type=integer, minval=1, defval=14)

rwiHigh = (high - nz(low[length])) / (atr(length) * sqrt(length))
rwiLow = (nz(high[length]) - low) / (atr(length) * sqrt(length))

plot(rwiHigh, title="High", linewidth=2, color=#6d1e7f, transp=0)
plot(rwiLow, title="Low", linewidth=2, color=#ff3737, transp=0)
