//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Rapid RSI script may be freely distributed under the MIT license.
study("Rapid RSI", shorttitle="RRSI")

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

upSum = sum(max(change(src), 0), length)
downSum = sum(max(-change(src), 0), length)

rrsi = downSum == 0 ? 100 : upSum == 0 ? 0 : 100 - (100 / (1 + upSum / downSum))

plot(rrsi, title="RRSI", linewidth=1, color=#6d1e7f, transp=0)

overboughtLevel = hline(title="Overbought Level", price=70)
oversoldLevel = hline(title="Oversold Level", price=30)

fill(title="Background", hline1=overboughtLevel, hline2=oversoldLevel, color=purple, transp=90)
