//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Relative Spread Strength script may be freely distributed under the MIT license.
study("Relative Spread Strength", shorttitle="RSS")

rsiLength = input(title="RSI Length", type=integer, defval=14, minval=1)
fastLength = input(title="Fast MA Length", type=integer, defval=10, minval=1)
slowLength = input(title="Slow MA Length", type=integer, defval=40, minval=1)
smoothingLength = input(title="Smoothing Length", type=integer, defval=5, minval=1)
useEMA = input(title="Use EMA?", type=bool, defval=true)
highLevel = input(title="High Level", type=integer, defval=80, maxval=100)
lowLevel = input(title="Low Level", type=integer, defval=20, minval=0)
src = input(title="Source", type=source, defval=close)

spread = useEMA ? ema(src, fastLength) - ema(src, slowLength) : sma(src, fastLength) - sma(src, slowLength)

rs = rsi(spread, rsiLength)
rss = sma(rs, smoothingLength)

plot(rss, title="RSS", linewidth=2, color=#e69138, transp=0)

hline(title="High Level", price=highLevel, linestyle=dotted, color=#ff0000)
hline(title="Low Level", price=lowLevel, linestyle=dotted, color=#ff0000)
