//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Trend Detection Index script may be freely distributed under the MIT license.
study("Trend Detection Index", shorttitle="TDI")

length = input(title="Length", type=integer, minval=1, defval=20)
src = input(title="Source", type=source, defval=close)

momentum = change(src, length)

tdi = abs(sum(momentum, length)) - (sum(abs(momentum), length * 2) - sum(abs(momentum), length))

// Direction Indicator
direction = sum(momentum, length)

plot(tdi, title="TDI", color=#ff0000, transp=0)
plot(direction, title="Direction", color=#0ebb23, transp=0)

hline(0, title="Zero Level", linestyle=dotted)
