//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Trend Continuation Factor script may be freely distributed under the MIT license.
study("Trend Continuation Factor", shorttitle="TCF")

length = input(title="Length", type=integer, minval=1, defval=35)
src = input(title="Source", type=source, defval=close)

plusChange(src) => change(src) > 0 ? change(src) : 0.0
minusChange(src) => change(src) > 0 ? 0.0 : -change(src)

plusCF = 0.0
plusCF := plusChange(src) == 0 ? 0.0 : plusChange(src) + nz(plusCF[1])

minusCF = 0.0
minusCF := minusChange(src) == 0 ? 0.0 : minusChange(src) + nz(minusCF[1])

plusTCF = sum(plusChange(src) - minusCF, length)
minusTCF = sum(minusChange(src) - plusCF, length)

plot(plusTCF, title="+TCF", linewidth=2, color=#38761d, transp=0)
plot(minusTCF, title="-TCF", linewidth=2, color=#cc4125, transp=0)

hline(0, title="Zero Level", linestyle=line, color=#e69138)
