//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Vertical Horizontal Filter script may be freely distributed under the MIT license.
study("Vertical Horizontal Filter", shorttitle="VHF")

length = input(title="Length", type=integer, defval=28, minval=1)
src = input(title="Source", type=source, defval=close)

vhf = abs(highest(src, length) - lowest(src, length)) / sum(abs(change(src)), length)

plot(vhf, title="VHF", linewidth=1, color=#674ea7, transp=0)
