//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Volatility Ratio indicator script may be freely distributed under the MIT license.
study("Volatility Ratio", shorttitle="VR")

length = input(title="Length", type=integer, defval=14, minval=1)
breakoutLevel = input(title="Breakout Level", type=float, defval=0.5, minval=0.0, step=0.1)

max = max(highest(high, length), close[length + 1])
min = min(lowest(low, length), close[length + 1])

vr = tr(true) / (max - min)

vrColor = vr >= breakoutLevel ? #39b361 : #cc4125

plot(vr, title="VR", linewidth=2, color=vrColor, transp=0)

hline(title="Breakout Level", price=breakoutLevel, linestyle=dotted, color=gray)
