//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Stoller Average Range Channels (STARC) Bands script may be freely distributed under the MIT license.
study("Stoller Average Range Channels (STARC) Bands", shorttitle="STARC", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=6)
maInput = input(title="MA", defval="SMA", options=["EMA", "SMA", "VWMA", "WMA"])
atrLength = input(title="ATR Length", type=integer, minval=1, defval=15)
mult = input(title="Multiplier", type=float, step=0.1, defval=1.33)
src = input(title="Source", type=source, defval=close)

basis = iff(maInput == "EMA", ema(src, length),
	 iff(maInput == "SMA", sma(src, length),
	 iff(maInput == "VWMA", vwma(src, length),
	 iff(maInput == "WMA", wma(src, length),
	 na))))

upperBand = basis + atr(length) * mult
lowerBand = basis - atr(length) * mult

plot(upperBand, title="Upper", linewidth=2, color=blue, transp=0)
plot(basis, title="Basis", linewidth=2, color=#6d1e7f, transp=0)
plot(lowerBand, title="Lower", linewidth=2, color=red, transp=0)
