//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Gopalakrishnan Range Index script may be freely distributed under the terms of GPL-3.0 license.
study("Gopalakrishnan Range Index", shorttitle="GAPO")

length = input(title="Length", type=integer, defval=5)

gapo = log(highest(length) - lowest(length)) / log(length)

gapoColor = gapo >= gapo[1] ? #0ebb23 : red
plot(gapo, title="GAPO", linewidth=2, color=gapoColor, transp=0)
