//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Accelerator Oscillator script may be freely distributed under the terms of GPL-3.0 license.
study("Accelerator Oscillator", shorttitle="AC")

fastLength = input(title="Fast Length", type=integer, defval=5)
slowLength = input(title="Slow Length", type=integer, defval=34)
smoothLength = input(title="Smoothing Length", type=integer, defval=5)

ao = sma(hl2, fastLength) - sma(hl2, slowLength)

ac = ao - sma(ao, smoothLength)

acColor = ac >= 0 ? (ac[1] < ac ? #26A69A : #B2DFDB) : (ac[1] < ac ? #FFCDD2 : #EF5350)
plot(ac, title="AC", style=columns, color=acColor, transp=0)
