//@version=4
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Adaptive RSI Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Adaptive RSI Moving Average", shorttitle="ARSIMA", overlay=true)

length = input(title="Length", type=input.integer, defval=14)
src = input(title="Source", type=input.source, defval=close)
highlight = input(title="Highlight ?", type=input.bool, defval=true)

alpha = 2 * abs(rsi(src, length) / 100 - 0.5)

arsima = 0.0
arsima := alpha * src + (1 - alpha) * nz(arsima[1])

arsimaColor = highlight ? arsima > arsima[1] ? color.green : color.red : #6d1e7f
plot(arsima, title="ARSIMA", linewidth=2, color=arsimaColor, transp=0)
