//@version=3
// Copyright (c) 2019-present, Alex Orekhov (everget)
// Double Weighted Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Double Weighted Moving Average", shorttitle="DWMA", overlay=true)

length = input(title="Length", type=integer, defval=10)
highlightMovements = input(title="Highlight Movements ?", type=bool, defval=true)
src = input(title="Source", type=source, defval=close)

dwma = wma(wma(src, length), length)

dwmaColor = highlightMovements ? (dwma > dwma[1] ? green : red) : #6d1e7f
plot(dwma, title="DWMA", linewidth=2, color=dwmaColor, transp=0)
