//@version=4
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Elastic Volume Weighted Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Elastic Volume Weighted Moving Average", shorttitle="EVWMA", overlay=true)

length = input(title="Length", type=input.integer, defval=14)
src = input(title="Source", type=input.source, defval=close)
highlight = input(title="Highlight ?", type=input.bool, defval=true)

volumeSum = sum(volume, length)

evwma = 0.0
evwma := ((volumeSum - volume) * nz(evwma[1]) + volume * src) / volumeSum

evwmaColor = highlight ? evwma > evwma[1] ? color.green : color.red : #6d1e7f
plot(evwma, title="EVWMA", linewidth=2, color=evwmaColor, transp=0)
