//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Fibonacci Weighted Moving Average script may be freely distributed under the GPL-3.0 license.
study("Fibonacci Weighted Moving Average", shorttitle="FWMA", overlay=true)

length = input(title="Length", type=integer, defval=14)
src = input(title="Source", type=source, defval=close)

phi = (1 + sqrt(5)) / 2

fiboWeight(i) =>
    pow = pow(phi, i)
    (pow - pow(-1, i) / pow) / sqrt(5)

fwma(src, length) =>
    sum = 0.0
    weightSum = 0.0

    for i = 0 to length - 1
        weight = fiboWeight(length - i)
        sum := sum + nz(src[i]) * weight
        weightSum := weightSum + weight

    sum / weightSum

plot(fwma(src, length), title="FWMA", linewidth=2, color=#741b47, transp=0)
