//@version=3
// Copyright (c) 1998-present, Dennis McNicholl
// Copyright (c) 2019-present, Alex Orekhov (everget)
// McNicholl Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("McNicholl Moving Average", shorttitle="MNMA", overlay=true)

length = input(title="Length", type=integer, defval=20)
highlightMovements = input(title="Highlight Movements ?", type=bool, defval=true)
src = input(title="Source", type=source, defval=close)

alpha = 2 / (length + 1)

ema1 = ema(src, length)
ema2 = ema(ema1, length)

mnma = ((2 - alpha) * ema1 - ema2) / (1 - alpha)

mnmaColor = highlightMovements ? (mnma > mnma[1] ? green : red) : #6d1e7f
plot(mnma, title="MNMA", linewidth=2, color=mnmaColor, transp=0)
