//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Middle-High-Low Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Middle-High-Low Moving Average", shorttitle="MHLMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
mhlRange = input(title="High-Low Range", type=integer, defval=10)
maType = input(title="MA Type", defval="EMA", options=["EMA", "SMA"])
highlightMovements = input(title="Highlight Movements ?", type=bool, defval=true)

mhl = avg(highest(mhlRange), lowest(mhlRange))
mhlma = maType == "EMA" ? ema(mhl, length) : sma(mhl, length)

mhlmaColor = highlightMovements ? (mhlma > mhlma[1] ? green : red) : #6d1e7f

plot(mhlma, title="MHLMA", linewidth=2, color=mhlmaColor, transp=0)
