//@version=4
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Moving Median script may be freely distributed under the terms of the GPL-3.0 license.
study("Moving Median", shorttitle="MM", overlay=true)

length = input(title="Length", type=input.integer, defval=14)
highlight = input(title="Highlight ?", type=input.bool, defval=true)
src = input(title="Source", type=input.source, defval=close)

median = percentile_nearest_rank(src, length, 50)

medianColor = highlight ? median > median[1] ? color.green : color.red : #6d1e7f
plot(median, title="MM", linewidth=2, color=medianColor, transp=0)
