//@version=3
// Copyright (c) 2019-present, Alex Orekhov (everget)
// Parabolic Weighted Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Parabolic Weighted Moving Average", shorttitle="PWMA", overlay=true)

length = input(title="Length", type=integer, defval=14)
power = input(title="Power", type=integer, minval=0, defval=2)
highlightMovements = input(title="Highlight Movements ?", type=bool, defval=true)
src = input(title="Source", type=source, defval=close)

sum = 0.0
weightSum = 0.0

for i = 0 to length - 1
	weight = pow(length - i, power)
	sum := sum + nz(src[i]) * weight
	weightSum := weightSum + weight

pwma = sum / weightSum

pwmaColor = highlightMovements ? (pwma > pwma[1] ? green : red) : #6d1e7f
plot(pwma, title="PWMA", linewidth=2, color=pwmaColor, transp=0)
