//@version=3
// Copyright (c) 2010-present, Bruno Pio
// Copyright (c) 2019-present, Alex Orekhov (everget)
// Pentuple Exponential Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Pentuple Exponential Moving Average", shorttitle="PEMA", overlay=true)

length = input(title="Length", type=integer, defval=20)
highlightMovements = input(title="Highlight Movements ?", type=bool, defval=true)
src = input(title="Source", type=source, defval=close)

ema1 = ema(src, length)
ema2 = ema(ema1, length)
ema3 = ema(ema2, length)
ema4 = ema(ema3, length)
ema5 = ema(ema4, length)
ema6 = ema(ema5, length)
ema7 = ema(ema6, length)
ema8 = ema(ema7, length)

pema = 8 * ema1 - 28 * ema2 + 56 * ema3 - 70 * ema4 + 56 * ema5 - 28 * ema6 + 8 * ema7 - ema8

pemaColor = highlightMovements ? (pema > pema[1] ? green : red) : #6d1e7f
plot(pema, title="PEMA", linewidth=2, color=pemaColor, transp=0)
