//@version=3
// Copyright (c) 2010-present, Bruno Pio
// Copyright (c) 2019-present, Alex Orekhov (everget)
// Quadruple Exponential Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Quadruple Exponential Moving Average", shorttitle="QEMA", overlay=true)

length = input(title="Length", type=integer, defval=20)
highlightMovements = input(title="Highlight Movements ?", type=bool, defval=true)
src = input(title="Source", type=source, defval=close)

ema1 = ema(src, length)
ema2 = ema(ema1, length)
ema3 = ema(ema2, length)
ema4 = ema(ema3, length)
ema5 = ema(ema4, length)

qema = 5 * ema1 - 10 * ema2 + 10 * ema3 - 5 * ema4 + ema5

qemaColor = highlightMovements ? (qema > qema[1] ? green : red) : #6d1e7f
plot(qema, title="QEMA", linewidth=2, color=qemaColor, transp=0)
