//@version=4
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Recursive Moving Trend Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Recursive Moving Trend Average", shorttitle="RMTA", overlay=true)

length = input(title="Length", type=input.integer, defval=14, minval=1)
src = input(title="Source", type=input.source, defval=close)
highlight = input(title="Highlight ?", type=input.bool, defval=true)

alpha = 2 / (length + 1)

b = 0.0
b := (1 - alpha) * nz(b[1], src) + src

rmta = 0.0
rmta := (1 - alpha) * nz(rmta[1], src) + alpha * (src + b - nz(b[1]))

rmtaColor = highlight ? rmta > rmta[1] ? color.green : color.red : #6d1e7f
plot(rmta, title="RMTA", linewidth=2, color=rmtaColor, transp=0)
