//@version=3
// Copyright (c) 2019-present, Alex Orekhov (everget)
// Self-Weighted Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Self-Weighted Moving Average", shorttitle="SEWMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
highlightMovements = input(title="Highlight Movements ?", type=bool, defval=false)
src = input(title="Source", type=source, defval=close)

sum = 0.0
weightSum = 0.0

for i = 0 to length - 1
	weight = src[length + i]
	weightSum := weightSum + weight
	sum := sum + weight * src[i]

sewma = sum / weightSum

sewmaColor = highlightMovements ? (sewma > sewma[1] ? green : red) : #6d1e7f
plot(sewma, title="SEWMA", linewidth=2, color=sewmaColor, transp=0)
