//@version=4
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Sharp Modified Moving Average script may be freely distributed under the terms of the GPL-3.0 license.
study("Sharp Modified Moving Average", shorttitle="SHMMA", overlay=true)

length = input(title="Length", type=input.integer, defval=14)
src = input(title="Source", type=input.source, defval=close)
highlight = input(title="Highlight ?", type=input.bool, defval=true)

factor = 0.0
slope = 0.0

for i = 1 to length
	factor := 1 + 2 * (i - 1)
	slope := slope + src[i - 1] * (length - factor) / 2

shmma = sma(src, length) + 6 * slope / ((length + 1) * length)

shmmaColor = highlight ? shmma > shmma[1] ? color.green : color.red : #6d1e7f
plot(shmma, title="SHMMA", linewidth=2, color=shmmaColor, transp=0)
