//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Triangular Moving Average script may be freely distributed under the GPL-3.0 license.
study("Triangular Moving Average", shorttitle="TMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=20)
highlightMovements = input(title="Highlight Movements ?", type=bool, defval=true)
src = input(title="Source", type=source, defval=close)

tma = sma(sma(src, ceil(length / 2)), floor(length / 2) + 1)
tmaColor = highlightMovements ? (tma > tma[1] ? green : red) : #6d1e7f

plot(tma, title="TMA", linewidth=2, color=tmaColor, transp=0)
