//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// All-Time High Days script may be freely distributed under the terms of GPL-3.0 license.
study("All-Time High Days", shorttitle="ATH Days", precision=0)

highlightATH = input(title="Highlight ATH ?", defval=false)

ath = high
ath := na(ath[1]) ? ath : (high > ath[1] ? high : ath[1])

cond = high == ath
transparent = color(white, 100)

bars = barssince(cond)
plot(bars, title="ATH Days", color=#674ea7)

bgcolor(cond and highlightATH ? orange : transparent)
