//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Adaptive RSI indicator script may be freely distributed under the MIT license.
study("Adaptive RSI", shorttitle="ARSI", overlay=true)

length = input(title="Length", type=integer, defval=14, minval=1)
src = input(title="Source", type=source, defval=close)

alpha = abs(rsi(src, length) / 100 - 0.5) * 2

arsi = 0.0
arsi := alpha * src + (1 - alpha) * nz(arsi[1])

plot(arsi, title="ARSI", color=#741b47, linewidth=2, transp=0)
