//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Ahrens Moving Average script may be freely distributed under the MIT license.
study("Ahrens Moving Average", shorttitle="AhMA", overlay=true)

length = input(title="Length", type=integer, defval=9, minval=1)
src = input(title="Source", type=source, defval=close)

ahma = 0.0
ahma := nz(ahma[1]) + (src - (nz(ahma[1]) + nz(ahma[length])) / 2) / length

plot(ahma, title="AhMA", linewidth=2, color=#6d1e7f, transp=0)
