//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Arnaud Legoux Moving Average script may be freely distributed under the MIT license.
study("Arnaud Legoux Moving Average", shorttitle="ALMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=9)
offset = input(title="Offset", type=float, defval=0.85)
sigma = input(title="Sigma", type=float, defval=6)
src = input(title="Source", type=source, defval=close)

plot(alma(src, length, offset, sigma), title="ALMA", linewidth=2, color=#e69138, transp=0)
