//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Ehlers Distance Coefficient Filter script may be freely distributed under the MIT license.
study("Ehlers Distance Coefficient Filter", shorttitle="EDCF", overlay=true)

length = input(title="Length", type=integer, defval=14)
src = input(title="Source", type=source, defval=hl2)

srcSum = 0.0
coefSum = 0.0

for count = 0 to length - 1
	distance = 0.0

	for lookback = 1 to length - 1
		distance := distance + pow(src[count] - src[count + lookback], 2)

	srcSum := srcSum + distance * src[count]
	coefSum := coefSum + distance

dcf = coefSum != 0 ? srcSum / coefSum : 0.0

plot(dcf, title="EDCF", linewidth=2, color=#6d1e7f, transp=0)
