//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Double Exponential Moving Average script may be freely distributed under the MIT license.
study("Double Exponential Moving Average", shorttitle="DEMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

dema(src, length) =>
	ema1 = ema(src, length)
	ema2 = ema(ema1, length)
	dema = 2 * ema1 - ema2

plot(dema(src, length), title="DEMA", linewidth=2, color=#6d1e7f, transp=0)
