//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Elastic Volume Weighted Moving Average script may be freely distributed under the MIT license.
study("Elastic Volume Weighted Moving Average", shorttitle="EVWMA", overlay=true)

length = input(title="Length", type=integer, defval=14, minval=1)
src = input(title="Source", type=source, defval=close)

volumeSum = sum(volume, length)

evwma = 0.0
evwma := ((volumeSum - volume) * nz(evwma[1]) + volume * src) / volumeSum

plot(evwma, title="EVWMA", linewidth=2, color=#6d1e7f, transp=0)
