//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Finite Impulse Response (FIR) Filter script may be freely distributed under the MIT license.
study("Finite Impulse Response (FIR) Filter", shorttitle="FIRF", overlay=true)

coef1 = input(title="1st Coefficient", type=float, defval=1, step=0.1)
coef2 = input(title="2nd Coefficient", type=float, defval=3.5, step=0.1)
coef3 = input(title="3rd Coefficient", type=float, defval=4.5, step=0.1)
coef4 = input(title="4th Coefficient", type=float, defval=3, step=0.1)
coef5 = input(title="5th Coefficient", type=float, defval=0.5, step=0.1)
coef6 = input(title="6th Coefficient", type=float, defval=-0.5, step=0.1)
coef7 = input(title="7th Coefficient", type=float, defval=-1.5, step=0.1)
src = input(title="Source", type=source, defval=close)

coefSum = coef1 + coef2 + coef3 + coef4 + coef5 + coef6 + coef7

firf = (coef1 * src + coef2 * nz(src[1]) + coef3 * nz(src[2]) + coef4 * nz(src[3]) + coef5 * nz(src[4]) + coef6 * nz(src[5]) + coef7 * nz(src[6])) / coefSum

plot(firf, title="IIRF", linewidth=2, color=#741b47, transp=0)
