//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Holt Exponential Moving Average script may be freely distributed under the MIT license.
study("Holt Exponential Moving Average", shorttitle="HEMA", overlay=true)

alphaLength = input(title="Alpha Length", type=integer, defval=20, minval=1)
gammaLength = input(title="Gamma Length", type=integer, defval=20, minval=1)
src = input(title="Source", type=source, defval=close)

alpha = 2 / (alphaLength + 1)
gamma = 2 / (gammaLength + 1)

b = 0.0
hema = 0.0

hema := (1 - alpha) * (nz(hema[1]) + nz(b[1])) + alpha * src
b := (1 - gamma) * nz(b[1]) + gamma * (hema - nz(hema[1]))

plot(hema, title="HEMA", linewidth=2, color=#6d1e7f, transp=0)
