//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Hull Moving Average script may be freely distributed under the MIT license.
study("Hull Moving Average", shorttitle="HMA", overlay=true)

length = input(title="Length", type=integer, defval=14, minval=1)
src = input(title="Source", type=source, defval=close)

hma(src, length) =>
	wma(2 * wma(src, length / 2) - wma(src, length), round(sqrt(length)))

plot(hma(src, length), title="HMA", linewidth=2, color=#6d1e7f, transp=0)
