//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Moving Geometric Mean script may be freely distributed under the MIT license.
study("Moving Geometric Mean", shorttitle="MGM", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

mgm(src, length) =>
	exp(sum(log(src), length) / length)

plot(mgm(src, length), title="MGM", linewidth=2, color=#6d1e7f, transp=0)
