//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Moving Median script may be freely distributed under the MIT license.
study("Moving Median", shorttitle="MM", overlay=true)

length = input(title="Length", type=integer, defval=14, minval=1)
src = input(title="Source", type=source, defval=close)

median(src, length) =>
	percentile_nearest_rank(src, length, 50)

plot(median(src, length), title="MM", linewidth=2, color=#6d1e7f, transp=0)
