//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Moving Quadratic Mean (RMS) script may be freely distributed under the MIT license.
study("Moving Quadratic Mean (RMS)", shorttitle="RMS", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

rms(src, length) =>
	sqrt(sum(src * src, length) / length)

plot(rms(src, length), title="RMS", linewidth=2, color=#6d1e7f, transp=0)
