//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Sharp Modified Moving Average script may be freely distributed under the MIT license.
study("Sharp Modified Moving Average", shorttitle="ShMMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

factor = 0.0
slope = 0.0

for i = 1 to length
	factor := 1 + 2 * (i - 1)
	slope := slope + (src[i - 1]) * (length - factor) / 2

shmma = sma(src, length) + (6 * slope) / ((length + 1) * length)

plot(shmma, title="ShMMA", linewidth=2, color=#6d1e7f, transp=0)
