//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Sine Weighted Moving Average script may be freely distributed under the MIT license.
study("Sine Weighted Moving Average", shorttitle="SWMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=20)
src = input(title="Source", type=source, defval=close)

swma(src, length) =>
	PI = 2 * asin(1)
	sum = 0.0
	weightSum = 0.0

	for i = 0 to length - 1
		weight = sin(i * PI / (length + 1))
		sum := sum + nz(src[i]) * weight
		weightSum := weightSum + weight

	sum / weightSum

plot(swma(src, length), title="SWMA", linewidth=2, color=#741b47, transp=0)
