//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Triangular Moving Average indicator script may be freely distributed under the MIT license.
study("Triangular Moving Average", shorttitle="TMA", overlay=true)

length = input(title="Length", type=integer, defval=20, minval=1)
src = input(title="Source", type=source, defval=close)

tma = sma(sma(src, ceil(length / 2)), floor(length / 2) + 1)

plot(tma, title="TMA", linewidth=2, color=#741b47, transp=0)
