//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Triangular Moving Average script may be freely distributed under the MIT license.
study("Triangular Moving Average", shorttitle="TMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=20)
src = input(title="Source", type=source, defval=close)

tma(src, length) =>
	sma(sma(src, ceil(length / 2)), floor(length / 2) + 1)

plot(tma(src, length), title="TMA", linewidth=2, color=#741b47, transp=0)
