//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Weighted Moving Average script may be freely distributed under the MIT license.
study("Weighted Moving Average", shorttitle="WMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

plot(wma(src, length), title="WMA", linewidth=2, color=#6d1e7f, transp=0)
