//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Wilder Modified Moving Average script may be freely distributed under the MIT license.
study("Wilder Modified Moving Average", shorttitle="WMMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=14)
src = input(title="Source", type=source, defval=close)

plot(rma(src, length), title="WMMA", linewidth=2, color=#6d1e7f, transp=0)
