//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Zero Lag Exponential Moving Average script may be freely distributed under the MIT license.
study("Zero Lag Exponential Moving Average", shorttitle="ZLEMA", overlay=true)

length = input(title="Length", type=integer, minval=1, defval=20)
src = input(title="Source", type=source, defval=close)

zlema(src, length) =>
	lag = round((length - 1) / 2)
	zlema = ema(src + (src - nz(src[lag])), length)

plot(zlema(src, length), title="ZLEMA", linewidth=2, color=#741b47, transp=0)
