//@version=3
// Copyright (c) 2018-present, Alex Orekhov (everget)
// Zero Lag Exponential Moving Average indicator script may be freely distributed under the MIT license.
study("Zero Lag Exponential Moving Average", shorttitle="ZLEMA", overlay=true)

length = input(title="Length", type=integer, defval=20, minval=1)
src = input(title="Source", type=source, defval=close)

lag = round((length - 1) / 2)

zlema = ema(src + (src - src[lag]), length)

plot(zlema, title="ZLEMA", linewidth=2, color=#741b47, transp=0)
